package border.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import border.model.AdminUnitTypeSubordination;

/*
 * Implementing a data access layer of an application has been cumbersome for quite a while. 
 * Too much boilerplate code has to be written to execute simple queries as well as perform pagination, and auditing. 
 * Spring JPA aims to significantly improve the implementation of data access layers by 
 * reducing the effort to the amount that's actually needed. As a developer you write your repository interfaces, 
 * including custom finder methods, and Spring will provide the implementation automatically. 
 * Source: http://www.springsource.org/spring-data/jpa
 * 
 * so the logic goes like this
 * 1 - declare custom interface, where you define your custom methods for jpa
 * 2 - define a class where you implement them cusom interface
 * 3 - declare interface for repository which extends JpaRepository and your custom interface
 * 4 - spring will magicaly create a bean (class) out of it, including methods from both interfaces
 * 5 - use this magic class in your service implementation
 *  
 */

public interface AdminUnitTypeSubordinationRepository extends
		JpaRepository<AdminUnitTypeSubordination, Long>, AdminUnitTypeRepositoryCustom {

//	CREATE MEMORY TABLE PUBLIC.ADMINUNITTYPE(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,CHANGEDBY VARCHAR(255),CHANGEDDATE TIMESTAMP NOT NULL,
//			CLOSEDBY VARCHAR(255),CLOSEDDATE TIMESTAMP NOT NULL,CODE VARCHAR(255),COMMENT VARCHAR(255),FROMDATE TIMESTAMP NOT NULL,NAME VARCHAR(255),OPENEDBY VARCHAR(255),
//			OPENEDDATE TIMESTAMP NOT NULL,TODATE TIMESTAMP NOT NULL)	

//	CREATE MEMORY TABLE PUBLIC.ADMINUNITTYPESUBORDINATION(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,CHANGEDBY VARCHAR(255),CHANGEDDATE TIMESTAMP NOT NULL,
//			CLOSEDBY VARCHAR(255),CLOSEDDATE TIMESTAMP NOT NULL,COMMENT VARCHAR(255),OPENEDBY VARCHAR(255),OPENEDDATE TIMESTAMP NOT NULL,MASTERADMINUNITTYPEID BIGINT,
//			SUBORDINATEADMINUNITTYPEID BIGINT,CONSTRAINT FK1B31BB02B379C6AC FOREIGN KEY(MASTERADMINUNITTYPEID) REFERENCES PUBLIC.ADMINUNITTYPE(ID),
//			CONSTRAINT FK1B31BB02F3E6AC82 FOREIGN KEY(SUBORDINATEADMINUNITTYPEID) REFERENCES PUBLIC.ADMINUNITTYPE(ID))

	
	@Query(value = "select * from AdminUnitTypeSubordination  where MasterAdminUnitTypeID=(:adminUnitTypeID) and OpenedDate < NOW() and ClosedDate > NOW()", nativeQuery = true)
	List<AdminUnitTypeSubordination> findSubordinatesActiveNow(@Param("adminUnitTypeID") Long adminUnitTypeID);

}
