
drop table user_roles IF EXISTS;
drop table users IF EXISTS;

CREATE TABLE users (
  USER_ID INTEGER NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
);

CREATE TABLE user_roles (
  USER_ROLE_ID INTEGER NOT NULL PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  AUTHORITY VARCHAR(45) NOT NULL,
);

ALTER TABLE user_roles ADD CONSTRAINT FK8E488775CD6D1E00 FOREIGN KEY(USER_ID) REFERENCES users(USER_ID)

INSERT INTO users (USER_ID, USERNAME, PASSWORD, ENABLED)
    VALUES (1, 'admin', '356a192b7913b04c54574d18c28d46e6395428ab', TRUE);
 
INSERT INTO users (USER_ID, USERNAME, PASSWORD, ENABLED)
    VALUES (2, 'user', '356a192b7913b04c54574d18c28d46e6395428ab', TRUE);    

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
    VALUES (1, 1, 'ROLE_ADMIN');

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY)
    VALUES (2, 2, 'ROLE_USER');
